name: suite
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.43.0
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.3
  - pip=23.2.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - wheel=0.41.2
  - xz=5.2.6
  - pip:
    - alabaster==0.7.13
    - babel==2.12.1
    - beautifulsoup4==4.12.2
    - black==23.9.1
    - certifi==2023.7.22
    - cffi==1.15.1
    - charset-normalizer==3.2.0
    - click==8.1.7
    - coverage==7.3.1
    - cpymad==1.14.2
    - docutils==0.18.1
    - idna==3.4
    - imagesize==1.4.1
    - iniconfig==2.0.0
    - isort==5.12.0
    - jinja2==3.1.2
    - lark==1.1.7
    - latexcodec==2.0.1
    - markupsafe==2.1.3
    - minrpc==0.1.0
    - mypy-extensions==1.0.0
    - numpy==1.26.0
    - packaging==23.1
    - pandas==2.1.1
    - pathspec==0.11.2
    - platformdirs==3.10.0
    - pluggy==1.3.0
    - pybtex==0.24.0
    - pybtex-docutils==1.0.3
    - pycparser==2.21
    - pygments==2.16.1
    - pytest==7.4.2
    - pytest-cov==4.1.0
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - requests==2.31.0
    - ruff==0.0.291
    - scipy==1.11.2
    - six==1.16.0
    - snowballstemmer==2.2.0
    - soupsieve==2.5
    - sphinx==7.2.6
    - sphinx-codeautolink==0.15.0
    - sphinx-copybutton==0.5.2
    - sphinx-issues==3.0.1
    - sphinx-prompt==1.8.0
    - sphinx-rtd-theme==1.3.0
    - sphinxcontrib-applehelp==1.0.7
    - sphinxcontrib-bibtex==2.5.0
    - sphinxcontrib-devhelp==1.0.5
    - sphinxcontrib-htmlhelp==2.0.4
    - sphinxcontrib-jquery==4.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.6
    - sphinxcontrib-serializinghtml==1.1.9
    - tzdata==2023.3
    - urllib3==2.0.5
    - xdeps==0.4.2
    - xfields==0.13.1
    - xobjects==0.2.8
    - xpart==0.15.3
    - xtrack==0.42.0
